services:
  - type: web
    name: MyMoney_Pro_Daily_Financial_Management
    env: python
    plan: free
    branch: main

    buildCommand: |
      # Install frontend dependencies
      npm ci
      npm run build

      # Install backend dependencies
      pip install -r requirements.txt

    startCommand: gunicorn backend.app:app --workers ${WEB_CONCURRENCY:-3} --bind 0.0.0.0:$PORT

    envVars:
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: WEB_CONCURRENCY
        sync: false

    autoDeploy: true
